### ISSUE TITLE
Wie ist es denn zu manipulieren

### ISSUE THREAD

**Issue by siebertm** [DrNatoor/impftermine_saarland_bot#1]
Wie ist unser System denn zu manipulieren und was sollte denn daran geändert werden? Über responsible disclosure sind wir immer sehr froh. 

Aktuell sehe ich "nur" ein chromedriver script, dass sich durch die Seite klickt. Das mag vielleicht nicht moralisch einwandfrei sein im Sinne der Fairness den anderen Menschen gegenüber und den vielen Menschen, die sich den allerwertesten wund arbeiten damit die Menschen geimpft werden können.

Aber sonst?

LG

(gern auch per PM antworten wenn es um sicherheitsrelevante Dinge geht!)

**Comment by shroominic** [comment]
Das Problem beim aktuellen System ist, dass man als Informatiker mit sehr einfachen Methoden einen großen Vorteil gegenüber allen anderen hat. Um das Problem zu beheben könnte man zB die freiwerdenden Termine an zufällige Personen verteilen. Aktuell bekommt es die Person (der Bot) der am schnellsten ist. 

VG!
Dominic

**Comment by siebertm** [comment]
Hi Dominic,

das ist halt die Sache: hatten wir. Waren die Leute unzufrieden mit. Bauen wir etwas anderes, sind die Leute ebenso unzufrieden damit :-)

Fakt ist, dass wir einen recht guten Bot-Schutz haben, der auch die massiven Crawling-Versuche in den letzten Wochen erfolgreich blockiert hat (~0,5 Mio geblockte Anfragen pro Tag, Tendenz steigend). Fakt ist auch, dass jemand, der das Wissen und die Motivation besitzt, einen Klickbot zu programmieren, das umgehen kann. Im Zweifel sitzt du vorm Rechner und löst das Captcha zwischendurch selbst. 

Die Alternativen:
* Ein Captcha bei jedem Klick - aber dann sperren wir effektiv alle legitimen Nutzer aus
* Alles abschalten und keine Restebuchung anbieten - dann laufen die Impfzentren nicht auf voller Kapazität, weil viele Menschen ihre Impfungen aktuell woanders erhalten und ihre Termine absagen. Die Folge: ungenutzer Impfstoff.
* Lücken automatisch auffüllen: machen wir aktuell, aber aus Rücksicht auf die Planung der Menschen nicht so kurzfristig.

Da hängt halt alles irgendwie zusammen und Entscheidungen, die manchmal recht fragwürdig erscheinen sind - wenn man alle Zusammenhänge hat - dann doch nachvollziehbar.

Nichtsdestotrotz finde ich es super, wenn sich Leute kritisch mit unserer Arbeit auseinandersetzen, ohne dabei gleich toxisch oder destruktiv zu werden - mehr verlange ich eigentlich nie :-)

Vgl auch https://www.sr.de/sr/home/nachrichten/panorama/bots_blockieren_impf_nachrueck_termine_100.html

LG Micha

**Comment by shroominic** [comment]
Hey Micha,
ich versuche mal meine Idee von oben auszuformulieren, da ich denke, dass das eine funktionierende Alternative wäre.
Alle spontan freiwerdenden Termine werden zufällig an alle Personen verlost, die aktiv auf der Webseite sind und einen dieser Termine haben wollen. Um zu vermeiden, dass Bots sich anmelden kann mein eine sichere Authentifizierung verwenden, die immer nur eine Instanz pro verifizierte Person zulässt. Die Teilnahme ohne Anmeldung ist somit nicht möglich. Wenn eine ausgewählte Person einen Termin erhält, ist dieser für einen kleinen Zeitraum für den Account reserviert und muss innerhalb der Zeit bestätigt werden. Wenn das nicht passiert, wird der Termin erneut zufällig verteilt.
Ich hoffe meine Alternative ist verständlich erklärt und gerne melden wenn irgendetwas unklar ist.
VG!
Dominic
